# Generated by Django 5.1.3 on 2024-12-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('curso', models.IntegerField()),
                ('cualitativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion', models.CharField(max_length=50)),
                ('curso', models.IntegerField(default=1)),
                ('n_secciones', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pensum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(default=2024)),
                ('finalizacion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=8)),
                ('genero', models.CharField(max_length=10, null=True)),
                ('seccion', models.CharField(max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('flotante', models.BooleanField(default=False)),
                ('materias_reprobadas', models.IntegerField(default=0)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_momento', models.FloatField(null=True)),
                ('segundo_momento', models.FloatField(null=True)),
                ('tercer_momento', models.FloatField(null=True)),
                ('definitiva', models.FloatField(null=True)),
                ('revision', models.FloatField(null=True)),
                ('estado', models.CharField(max_length=10, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.materias')),
                ('periodos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.periodos')),
            ],
        ),
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_momento', models.CharField(max_length=3, null=True)),
                ('segundo_momento', models.CharField(max_length=3, null=True)),
                ('tercer_momento', models.CharField(max_length=3, null=True)),
                ('notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.notas')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pensum'),
        ),
        migrations.AddField(
            model_name='materias',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pensum'),
        ),
    ]
