# Generated by Django 5.1.3 on 2024-11-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion', models.CharField(max_length=50)),
                ('curso', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pensum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=6)),
                ('seccion', models.CharField(max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('materias_reprobadas', models.IntegerField(default=0)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_lapso', models.FloatField()),
                ('segundo_lapso', models.FloatField()),
                ('tercer_lapso', models.FloatField()),
                ('definitiva', models.FloatField()),
                ('revision', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.materias')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pensum'),
        ),
        migrations.AddField(
            model_name='materias',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pensum'),
        ),
    ]
