# Generated by Django 5.1.3 on 2024-11-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='definitiva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='primer_lapso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='revision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='segundo_lapso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='tercer_lapso',
            field=models.FloatField(null=True),
        ),
    ]
