# Generated by Django 5.1.3 on 2025-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='repitiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='inicio',
            field=models.IntegerField(default=2025),
        ),
    ]
