# Generated by Django 5.1.3 on 2024-12-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='n_cursos',
            new_name='n_secciones',
        ),
        migrations.AlterField(
            model_name='periodos',
            name='inicio',
            field=models.IntegerField(default=2024),
        ),
    ]
