<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-09 15:40
=======
# Generated by Django 5.1.3 on 2024-12-09 12:50
>>>>>>> refs/remotes/origin/master

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_notas_definitiva_alter_notas_primer_lapso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='primer_lapso',
            new_name='primer_momento',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='segundo_lapso',
            new_name='segundo_momento',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='tercer_lapso',
            new_name='tercer_momento',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='flotante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='genero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_momento', models.CharField(max_length=3, null=True)),
                ('segundo_momento', models.CharField(max_length=3, null=True)),
                ('tercer_momento', models.CharField(max_length=3, null=True)),
                ('notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.notas')),
            ],
        ),
    ]
