# Generated by Django 5.1.3 on 2024-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_primer_lapso_notas_primer_momento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='cualitativa',
            field=models.BooleanField(default=False),
        ),
    ]
