# Generated by Django 5.1.4 on 2024-12-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_materias_cualitativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ci',
            field=models.CharField(max_length=8),
        ),
    ]
